---
title: "Get Involved"
output: html_notebook
---

## Part 1: Join a PSU Club

This year I decided to join the Student Red Cross Club. In High School, I was very involved in my school’s Red Cross Club. I volunteered at blood drives and went around school a week in advance to get people to sign up to donate blood. Coming to college I knew I wanted to be apart of a volunteer club and since I loved the Red Cross Club in High School, I thought I would enjoy it in college too! At the first meeting, we learned exactly what the Student Red Cross Club does. The Student Red Cross Club runs all blood drives throughout the entire year on Penn State’s campus. Besides blood drives, the Student Red Cross Club also does outreach programs like Jared’s box and Totes of Hope to help people in the community. We also did an icebreaker where we got to meet others in the club. I really enjoyed the meeting and felt inspired to be a part of such a big volunteer club. I am still a member of the Student Red Cross Club and shortly after joining I applied and got the position as THON Captain. I was in charge of coming up with fundraisers to raise money for our Club’s Organization. In November, I was told to apply for an executive board position by past exec board members. So now I am the Treasurers of the Student Red Cross Club.  I am in charge of dealing with all the money and organizing the blood drives. I am so excited for this new role and what is in store for the club. It was one of the best decisions I made to join the Student Red Cross Club and I am so glad I did it!

## Part 2: Try New Things at PSU